### ISSUE TITLE
Add flag for some countries

### ISSUE THREAD

**Issue by Mirach0rus** [hjnilsson/country-flags#11]
Please add flag for next countries/places:
```
Ascension Island
Antarctica
Caribbean Netherlands
Bouvet Island
Clipperton Island
Diego Garcia
Ceuta & Melilla
Western Sahara
French Guiana
Guadeloupe
Heard & McDonald Islands
Canary Islands
St. Martin
St. Pierre & Miquelon
Svalbard & Jan Mayen
Tristan da Cunha
U.S. Outlying Islands
Wallis & Futuna
Kosovo
Mayotte
```

**Comment by hjnilsson** [comment]
We're only including countries with ISO 3166 codes. I have thus included Antartica (AQ), Western Sahara (EH), French Guiana (GF), Guadeloupe (GP), Saint Martin (MF), Saint Pierre and Miquelon (PM), Svalbard and Jan Mayen Islands (SJ), Mayotte (YT), Wallis and Futuna Islands (WF).

Most importantly: Kosovo does not yet have an ISO code. I included it as "Kosovo.svg" and added a comment in the readme.

**Comment by silverlight513** [comment]
Not sure if this is the right place to put this but I found some more missing flags. The 3 countries that make up most of the United Kingdom aren't included. Here's a link to their Wiki page https://en.wikipedia.org/wiki/ISO_3166-2:GB

**Comment by hjnilsson** [comment]
This is the correct place to ask. I've added the flags for Wales, Scotland and England (and reused the UK flag for Northern Ireland). Updated to version 1.1.0.

**Comment by crustamet** [comment]
Ascension Island
[ISO 3166 code](https://en.wikipedia.org/wiki/ISO_3166)
[SH-AC](https://en.wikipedia.org/wiki/ISO_3166-2:SH)
they have a unique flag also
3 flags 
SH-AC (Ascension Island)
SH-HL (Saint helena)
SH-TA (Tristan da Cunha)

please add them as they are like that
