### ISSUE TITLE
Optimize the size of png?

### ISSUE THREAD

**Issue by symac** [hjnilsson/country-flags#18]
The repository is very interesting but it seems that it should be improved by optimizing the png produced. I have tried https://tinypng.com/ on the biggest one from png250px and for all of them the optimized version is ~60% lighter without any difference being seen, even fullscreen on a desktop screen. Don't know what is the best way to apply that to all icons in the repository but that would be great.

**Comment by hjnilsson** [comment]
TinyPNG uses a proprietary compression that we can't reuse in a build script. Have you tried alternate PNG compression libraries on NPM instead? Maybe there is a gain to be made there. Right now imagemin is being used ( https://github.com/imagemin/imagemin ).

**Comment by hjnilsson** [comment]
Closing, since using tinning is not possible without paying for the service.
