### ISSUE TITLE
Consider using XK as country code for Kosovo

### ISSUE THREAD

**Issue by RudeySH** [hjnilsson/country-flags#22]
[Quote from Wikipedia](https://en.wikipedia.org/wiki/Kosovo):

> XK is a "user assigned" ISO 3166 code not designated by the standard, but used by the European Commission, Switzerland, the Deutsche Bundesbank and other organisations.

**Comment by hjnilsson** [comment]
Done via 10d1e6cb22c7ac58d4f1ba60ca7cadd7f74e08fb, thanks for the suggestion!
