### ISSUE TITLE
Thoughts on including the flag of the European Union?

### ISSUE THREAD

**Issue by RudeySH** [hjnilsson/country-flags#23]
While it's not a country, and it does not have an ISO 3166 code, I think it would fit right in. [Here's the SVG flag image from Wikipedia.](https://en.wikipedia.org/wiki/European_Union#/media/File:Flag_of_Europe.svg) It's country code should be "EU".

**Comment by hjnilsson** [comment]
Not really for using a non-standard country code, but maybe can be added with the name `Europe.svg` (like Kosovo was before)?

**Comment by RudeySH** [comment]
It's not a countrycode but `EU` is officially reserved, no future country will get that code assigned.

**Comment by hjnilsson** [comment]
This is now included. :)
