### ISSUE TITLE
The flag of Mauritania was changed.

### ISSUE THREAD

**Issue by RudeySH** [hjnilsson/country-flags#24]
This library is using [this one](https://github.com/hjnilsson/country-flags/blob/master/svg/mr.svg) currently. And [here's](https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg) the new one.

**Comment by hjnilsson** [comment]
Flag updated in 15ebf9a0c728c8b7f3e6761b286281eacaba354d, will push a new minor version to NPM soon. Thanks!
