### ISSUE TITLE
Add flags for countries which has been deleted from 3166-1 and are part of 3166-3

### ISSUE THREAD

**Issue by KES777** [hjnilsson/country-flags#28]
[prof link](https://en.wikipedia.org/wiki/ISO_3166-3)

[CS](https://ru.wikipedia.org/wiki/%D0%A1%D0%B5%D1%80%D0%B1%D0%B8%D1%8F_%D0%B8_%D0%A7%D0%B5%D1%80%D0%BD%D0%BE%D0%B3%D0%BE%D1%80%D0%B8%D1%8F#/media/File:Flag_of_Serbia_and_Montenegro.svg), [SU](https://en.wikipedia.org/wiki/Soviet_Union#/media/File:Flag_of_the_Soviet_Union.svg) etc

**Comment by wyattoday** [comment]
The Soviet Union no longer exists (it has been replaced by a number of countries). "Transitional" codes reference things that no longer exist or have new codes. This repository isn't a historical list of all flags that have existed (good luck to anyone that wants to take on that enormous project), but rather a repository of flags of country-regions that exist currently on earth.

**Comment by KES777** [comment]
Why not? it will be useful if we want to print some history book or mention a country.

Probably move flags for such countries into another directory

**Comment by hjnilsson** [comment]
As Wyatt stated, that is not the scope of THIS project. You are free to start a `svg-historical-country-flags` and start working on creating that. But bloating this repository with hundreds of more flags that 99.99% of users are not interested in, is not a good idea.
