### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Garonenur** [hjnilsson/country-flags#32]
Hi,
this collection is great, could you add a license for them? It would make it more "secure" to use these.

**Comment by hjnilsson** [comment]
As stated in the README. Copyright law does not apply to flags, so licensing them would be illegal.

For laws surrounding flag use, wikipedia has an incomplete list: https://en.wikipedia.org/wiki/Flag_desecration

In general, you are not allowed to use the flag in advertising contexts.
