### ISSUE TITLE
Cannot import SVG in AI or Graphic

### ISSUE THREAD

**Issue by cpshanley** [hjnilsson/country-flags#37]
Is it me?

When I open the SVGs in Illustrator, they are all over the place.

Thanks

**Comment by hjnilsson** [comment]
Hello,

This is boxes the images does not have the viewBox property set to the same values.

If you could contribute, and set the viewBox to uniform values (ie. 1000 width / height), that would be great! :)

**Comment by hjnilsson** [comment]
This should be fixed thanks to PR #43
