### ISSUE TITLE
Flags by cioc

### ISSUE THREAD

**Issue by rotoxl** [hjnilsson/country-flags#45]
Hi! 

I've crossed them against the data at https://restcountries.eu/rest/v2/all to get a new collection of the flags named by its cioc, resulting in 203 flags.

I've forked your repo to https://github.com/rotoxl/country-flags to add 2 new folders, png100px_by_cioc and png250px_by_cioc, maybe you would like to add them to your repo.

Thank you very much for such a wonderful work. Good luck

**Comment by hjnilsson** [comment]
Thanks! Good work :)

**Comment by hjnilsson** [comment]
Due to the relatively large size increase of the resulting package, I won't merge this. The mapping can easily be done in software.
