### ISSUE TITLE
Please update the usage example

### ISSUE THREAD

**Issue by mbaraka** [hjnilsson/country-flags#48]
Can we please adjust the example to reflect the path changes in version [1.1.0] - 2018-12-24 ?

According to https://pub.dartlang.org/packages/country_icons#-changelog-tab-

I took awhile looking for the reason it is failing to load and trying to see the name, it would be great if we update the example.

Thank you for great library

**Comment by hjnilsson** [comment]
Hello, that is not the same repository as this is. Should be reported somewhere else. :)
