### ISSUE TITLE
What is the licence?

### ISSUE THREAD

**Issue by feduza** [hjnilsson/country-flags#50]
I want to know if I can use this in commercial project.

**Comment by Hessi9** [comment]
It looks like the Icons are from Wickimedia. At Wickimedia I learned that most countries have a low saying that the flag is not copy right protected. And at least in europe you can't get ownership or publishing rights for art you just copy. But to be shure you can search the individual flags of the countries you need at Wikimedia, read the copyless notice and take the icons from there.

**Comment by hjnilsson** [comment]
Yes. Flags are not copyrighted (by law). 

There are other restrictions on use though. Many countries forbid using the flag in some situations, but this will depend on your jursidiction.
