### ISSUE TITLE
AN is an old iso code

### ISSUE THREAD

**Issue by Danny-Engelman** [hjnilsson/country-flags#54]
https://en.wikipedia.org/wiki/ISO_3166-2:AN

**Comment by hjnilsson** [comment]
Code is reserved until 2060, until then, it will be included. :)

**Comment by Danny-Engelman** [comment]
By that standard you have to include many former nations.  

(alas I can't find one single page with all reserved codes)

from: https://www.iso.org/glossary-for-iso-3166.html

> Transitionally reserved codes – codes that are reserved during a transitional period while new code elements that may replace them are taken into use. This results from changes in the standard. For example, the country codes for the former Yugoslavia have been reserved when it was removed from ISO 3166-1.

![image](https://user-images.githubusercontent.com/3382713/71583535-2e544580-2b0f-11ea-9992-232a8a4f2b97.png)

AN - The Netherlands Antilles was divided in 2010

![image](https://user-images.githubusercontent.com/3382713/71583615-82f7c080-2b0f-11ea-9c23-78ca323d73db.png)
