### ISSUE TITLE
Take down suggestion of tw.svg

### ISSUE THREAD

**Issue by greatbody** [hjnilsson/country-flags#57]
# Intention

Please remove tw.svg from your repository.

It's an international agreement that Taiwan Province in a part of China(PRC).

# Reference

[Taiwan Province, People's Republic of China](https://en.wikipedia.org/wiki/Taiwan_Province,_People%27s_Republic_of_China)

# Thank you

Thank you for your effort in opensource movement.

**Comment by hjnilsson** [comment]
While true, it does not change the ISO standard. Many derelict flags are listed still, to remain backwards compatible.
