### ISSUE TITLE
El Salvador missing tildes

### ISSUE THREAD

**Issue by KevinMelendez** [hjnilsson/country-flags#62]
Two words in El Salvador's flag are missing tildes.

It should be: REPÚBLICA DE EL SALVADOR EN LA AMÉRICA CENTRAL
Currently it's showing: REPUBLICA DE EL SALVADOR EN LA AMERICA CENTRAL

[Wiki Source](https://en.wikipedia.org/wiki/Flag_of_El_Salvador)

**Comment by wyattoday** [comment]
Fixed & merged. https://github.com/hjnilsson/country-flags/pull/67
