### ISSUE TITLE
Any source for a list of "language spoken" associated with the flags?

### ISSUE THREAD

**Issue by plueschpruem** [hjnilsson/country-flags#73]
I know, it's not as easy as that - you often have many languages spoken, etc..
I'm interested in the "main" language associated with each country.
So GB and US would both be "English" (as well as many others).

If you have a good source, I would be willing to make the JSON to merge into this git for others with the same problem.

**Comment by wyattoday** [comment]
http://www.flagsarenotlanguages.com/blog/

**Comment by plueschpruem** [comment]
Nice link! Thanks a lot.
Good collection of the problems one runs into. Since it's only a "simple" use case, I guess I will thin the list and add languages myself, so the customer discussion can end :-)

**Comment by hjnilsson** [comment]
There is no easy mapping to be done here. For many countries, it will simply be wrong to map one language (like Switzerland). Not in scope for this repository.
