### ISSUE TITLE
missing script: build-pngs

### ISSUE THREAD

**Issue by dschinkel** [hjnilsson/country-flags#78]
I must be doing something dumb but got the error `missing script: build-pngs`

Here's what I did:

`npm install -g svgexport imagemin-cli`
`npm run build-pngs -- 20:`

I don't want to run this _manually_ so how can I get this working?

**Comment by wyattoday** [comment]
You’re probably not in the scripts folder, and thus not executing the JS. Hard to know. Can’t reproduce what you’re seeing.
