### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by zmullett** [hjnilsson/country-flags#79]
What is the intended license of this repo? Would you be willing to add a LICENSE file?
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

For example, if you're happy to apply a permissive license, you could use Apache License 2.0:
https://github.com/google/new-project/blob/master/LICENSE

**Comment by wyattoday** [comment]
https://github.com/hjnilsson/country-flags/issues/76

**Comment by zmullett** [comment]
Thanks for the quick response and apologies for not thoroughly checking the issues history. It might be worth including the reasoning behind being unable to apply a license somewhere prominently in the README.
