### ISSUE TITLE
No Flag

### ISSUE THREAD

**Issue by imithu** [hjnilsson/country-flags#81]
Add a no flag svg

**Comment by wyattoday** [comment]
Why?

**Comment by imithu** [comment]
in some cases, a "no flag" image is important. 


## Example 1
a developer developed an application where children will solve flag and country name. children will select the "no flag" image if they fail to solve.


## Example 2
in a sign-up webpage, a page will load the "no flag" image initially
for all country name, 
then all the country flags will be loaded.
this will ensure that the website page layout will not broken initially if that page fail to load a country flag.

**Comment by wyattoday** [comment]
Those are solvable problems in your app. There is no internationally recognized region with “no flag”.
